storage_config:
  boltdb_shipper:
    active_index_directory: /etc/loki/data/index
    cache_location: /etc/loki/data/boltdb-cache
    shared_store: filesystem

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /etc/loki/data/compactor
  shared_store: filesystem
