auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  instance_addr: 127.0.0.1
  path: /tmp/loki  # Carpeta con permisos
  storage:
    filesystem:
      directory: /tmp/loki/chunks
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

compactor:
  working_directory: /tmp/loki/compactor  # Carpeta con permisos
  shared_store: filesystem
  compaction_interval: 10m

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/index_cache
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  allow_structured_metadata: false
  retention_period: 336h  # 14 días

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h  # 14 días
